### ISSUE TITLE
broken link to code

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS-CoV-2-RBD_DMS_variants#25]
@WillHannon-MCB, your RBD heatmap links to the code at the following URL, which is broken: https://github.com/jbloomlab/SARS-CoV-2-RBD_DMS_variants/blob/visualizations/RBD-Heatmaps-Interactive-Visualization.ipynb

**Comment by WillHannon-MCB** [comment]
This should be resolved now.
